### PR TITLE
V0.3.8

### PR DESCRIPTION
**Pull request by bergundy**
Includes setup.py fix and version bump for 0.3.7.

Please upload this to pypi.

### CODE REVIEW

**Comment by advance512** [comment]
+1, please merge in

**Comment by bergundy** [comment]
Hey, thanks for merging.  Can you please upload this to pypi?

**Comment by bergundy** [comment]
@nerdynick, sorry for nagging but can you please upload this to pypi?

**Comment by nerdynick** [comment]
It should be uploaded now. I uploaded tar(Gz & Bz) and zip. Sorry for the delay, been a little busy.

**Comment by bergundy** [comment]
Thanks!

**Pull request merged**
